import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { About } from "./components/about";
import Hero from "./components/hero";
import Process from "./components/process";
import Connect from "./components/connect";
import { Text } from "./components/hover-text";
import { Projects } from "./components/projects";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Navbar />
        <Hero />
        <Process />
        <About />
        <Text />
        <Projects />
        <Connect />
        {children}
        <Footer />
      </body>
    </html>
  );
}
